# historic aviation scenario
# contrail module based on Megill & Grewe (2025)

# Species considered
[species]
# Species defined in emission inventories
# possible values: "CO2", "H2O", "NOx", "distance"
inv = ["CO2", "H2O", "NOx", "distance"]
# Output / response species
# possible values: "CO2", "H2O", "O3", "CH4", "PMO", "cont"
out = ["CO2", "H2O", "O3", "CH4", "PMO", "cont"]
# Assumed NOx species in emission inventory
# possible values: "NO", "NO2"
nox = "NO"

# Emission inventories                                                    
[inventories]
dir = "input/"
files = ["ELK_all-subsectors_2019_flat.nc"]
# base emission inventories, only considered if rel_to_base = true
rel_to_base = false
base.dir = "../repository/"
base.files = [
    "rnd_inv_2020.nc",
    "rnd_inv_2030.nc",
    "rnd_inv_2040.nc",
    "rnd_inv_2050.nc",
]

# Output options
[output]
# Full simulation run = true, climate metrics only = false
full_run = true
dir = "results/megill/hist_g0p50/"
name = "hist_g0p50"
overwrite = true
concentrations = false

# Time settings
[time]
dir = "input/"
# Time range in years: t_start, t_end, step, (t_end not included)
range = [1920, 2020, 1]
# Time evolution of emissions
# either type "scaling" or type "norm"
#file = "time_scaling_example.nc"
file = "time_norm_historic_SSP.nc"

# Background concentrations
[background]
dir = "../oac/repository/"
CO2.file = "co2_bg.nc"
CO2.scenario = "SSP2-4.5"
#CO2.file = "../repository/co2_bg_rcp.nc"
#CO2.scenario = "RCP2.6"
CH4.file = "ch4_bg.nc"
CH4.scenario = "SSP2-4.5"
N2O.file = "n2o_bg.nc"
N2O.scenario = "SSP2-4.5"

# Response options
[responses]
dir = "../oac/repository/"
CO2.response_grid = "0D"
CO2.conc.method = "Sausen&Schumann"
# RF method based on Etminan et al. 2016 is used by default.
#CO2.rf.method = "Etminan_2016"

H2O.response_grid = "2D"
H2O.rf.file = "resp_RF.nc"  # AirClim response surface

O3.response_grid = "2D"
O3.rf.file = "resp_RF_O3.nc"
#O3.rf.file = "resp_RF.nc"  # AirClim response surface, requires adjustment of CORR_RF_O3 ! 

CH4.response_grid = "2D"
CH4.tau.file = "resp_ch4.nc"
CH4.rf.method = "Etminan_2016"

cont.response_grid = "cont"
cont.method = "Megill_2025"
cont.resp.file = "resp_cont_lf.nc"
cont.G_250 = 0.50  # Pa/K
cont.eff_fac = 1.0  # efficiency factor compared to kerosene (1.0)
cont.PMrel = 1.0  # relative PM emissions compared to kerosene (1.0)
cont.debug.export = true

# Temperature options
[temperature]
# valid methods: "Boucher&Reddy"
method = "Boucher&Reddy"
# Climate sensitivity parameter, Ponater et al. 2006, Table 1
# https://doi.org/10.1016/j.atmosenv.2006.06.036
CO2.lambda = 0.73
# Efficacies, Ponater et al. 2006, Table 1
H2O.efficacy = 1.14
O3.efficacy = 1.37
PMO.efficacy = 1.37
CH4.efficacy = 1.14
cont.efficacy = 0.59

# Climate metrics options
[metrics]
# iterate over elements in lists types t_0 and H
types = ["ATR"] # valid climate metrics: AGWP, ATR
H = [51]       # Time horizon, t_final = t_0 + H - 1
t_0 = [1940]    # Start time for metrics calculation

# aircraft defined in inventory
[aircraft]
types = ["KER", "SAF", "LH2"]